ops_dir_config_params: &ops-dir-config-params
  OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
  OPSMAN_USERNAME: ((opsman_admin_username))
  OPSMAN_PASSWORD: ((opsman_admin_password))
  VCENTER_HOST: ((vcenter_host))
  VCENTER_USR: ((vcenter_usr))
  VCENTER_PWD: ((vcenter_pwd))
  VCENTER_DATA_CENTER: ((vcenter_data_center))
  VCENTER_DISK_TYPE: ((vm_disk_type))
  EPHEMERAL_STORAGE_NAMES: ((ephemeral_storage_names))
  PERSISTENT_STORAGE_NAMES: ((persistent_storage_names))
  BOSH_VM_FOLDER:  ((bosh_vm_folder))
  BOSH_TEMPLATE_FOLDER: ((bosh_template_folder))
  BOSH_DISK_PATH: ((bosh_disk_path))
  ICMP_CHECKS_ENABLED: ((icmp_checks_enabled))
  INFRA_NETWORK_NAME: ((infra_network_name))
  INFRA_VCENTER_NETWORK: ((infra_vsphere_network))
  INFRA_NW_CIDR: ((infra_nw_cidr))
  INFRA_EXCLUDED_RANGE: ((infra_excluded_range))
  INFRA_NW_DNS: ((infra_nw_dns))
  INFRA_NW_GATEWAY: ((infra_nw_gateway))
  INFRA_NW_AZS: ((infra_nw_azs))
  DEPLOYMENT_NETWORK_NAME: ((deployment_network_name))
  DEPLOYMENT_VCENTER_NETWORK: ((deployment_vsphere_network))
  DEPLOYMENT_NW_CIDR: ((deployment_nw_cidr))
  DEPLOYMENT_EXCLUDED_RANGE: ((deployment_excluded_range))
  DEPLOYMENT_NW_DNS: ((deployment_nw_dns))
  DEPLOYMENT_NW_GATEWAY: ((deployment_nw_gateway))
  DEPLOYMENT_NW_AZS: ((deployment_nw_azs))
  # PKS_NETWORK_NAME: ( (pks_network_name) )
  # PKS_VCENTER_NETWORK: ( (pks_vsphere_network) )
  # PKS_NW_CIDR: ( (pks_nw_cidr) )
  # PKS_EXCLUDED_RANGE: ( (pks_excluded_range) )
  # PKS_NW_DNS: ( (pks_nw_dns) )
  # PKS_NW_GATEWAY: ( (pks_nw_gateway) )
  # PKS_NW_AZS: ( (pks_nw_azs) )
  SERVICES_NETWORK_NAME: ((services_network_name))
  SERVICES_VCENTER_NETWORK: ((services_vsphere_network))
  SERVICES_NW_CIDR: ((services_nw_cidr))
  SERVICES_EXCLUDED_RANGE: ((services_excluded_range))
  SERVICES_NW_DNS: ((services_nw_dns))
  SERVICES_NW_GATEWAY: ((services_nw_gateway))
  SERVICES_NW_AZS: ((services_nw_azs))
  DYNAMIC_SERVICES_NETWORK_NAME: ((dynamic_services_network_name))
  DYNAMIC_SERVICES_VCENTER_NETWORK: ((dynamic_services_vsphere_network))
  DYNAMIC_SERVICES_NW_CIDR: ((dynamic_services_nw_cidr))
  DYNAMIC_SERVICES_EXCLUDED_RANGE: ((dynamic_services_excluded_range))
  DYNAMIC_SERVICES_NW_DNS: ((dynamic_services_nw_dns))
  DYNAMIC_SERVICES_NW_GATEWAY: ((dynamic_services_nw_gateway))
  DYNAMIC_SERVICES_NW_AZS: ((dynamic_services_nw_azs))
  AZ_1: ((az_1_name))
  AZ_1_CLUSTER_NAME: ((az_1_cluster_name))
  AZ_1_RP_NAME: ((az_1_rp_name))
  AZ_2: ((az_2_name))
  AZ_2_CLUSTER_NAME: ((az_2_cluster_name))
  AZ_2_RP_NAME: ((az_2_rp_name))
  AZ_3: ((az_3_name))
  AZ_3_CLUSTER_NAME: ((az_3_cluster_name))
  AZ_3_RP_NAME: ((az_3_rp_name))
  NTP_SERVERS: ((ntp_servers))
  ENABLE_VM_RESURRECTOR: ((enable_vm_resurrector))
  MAX_THREADS: ((max_threads))
  TRUSTED_CERTIFICATES: ((trusted_certificates))
  NSX_NETWORKING_ENABLED: ((nsx_networking_enabled))
  NSX_MODE: ((nsx_mode))
  NSX_ADDRESS: ((nsx_address))
  NSX_USERNAME: ((nsx_username))
  NSX_PASSWORD: ((nsx_password))

ert_config_params: &ert-config-params
  IAAS: vsphere
  OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
  OPSMAN_USERNAME: ((opsman_admin_username))
  OPSMAN_PASSWORD: ((opsman_admin_password))
  ERT_SINGLETON_JOB_AZ: ((ert_singleton_job_az))
  DEPLOYMENT_NW_AZS: ((deployment_nw_azs))
  NETWORK_NAME: ((deployment_network_name))
  ENABLE_SECURITY_EVENT_LOGGING: ((enable_security_event_logging))
  SYSLOG_HOST: ((syslog_host))
  SYSLOG_PORT: ((syslog_port))
  SYSLOG_PROTOCOL: ((syslog_protocol))
  SYSLOG_DRAIN_BUFFER_SIZE: ((syslog_drain_buffer_size))
  COMPANY_NAME: ((company_name))
  AUTHENTICATION_MODE: ((authentication_mode))
  LOGGREGATOR_ENDPOINT_PORT: ((loggregator_endpoint_port))
  SSL_CERT: ((ssl_cert))
  SSL_PRIVATE_KEY: ((ssl_private_key))
  SAML_SSL_CERT: ((saml_ssl_cert))
  SAML_SSL_PRIVATE_KEY: ((saml_ssl_private_key))
  HAPROXY_FORWARD_TLS: ((haproxy_forward_tls))
  HAPROXY_BACKEND_CA: ((haproxy_backend_ca))
  ROUTER_TLS_CIPHERS: ((router_tls_ciphers))
  HAPROXY_TLS_CIPHERS: ((haproxy_tls_ciphers))
  DISABLE_HTTP_PROXY: ((disable_http_proxy))
  TCP_ROUTING: ((tcp_routing))
  TCP_ROUTING_PORTS: ((tcp_routing_ports))
  ROUTE_SERVICES: ((route_services))
  IGNORE_SSL_CERT: ((ignore_ssl_cert_verification))
  SMTP_FROM: ((smtp_from))
  SMTP_ADDRESS: ((smtp_address))
  SMTP_PORT: ((smtp_port))
  SMTP_USER: ((smtp_user))
  SMTP_PWD: ((smtp_pwd))
  SMTP_AUTH_MECHANISM: ((smtp_auth_mechanism))
  LDAP_URL: ((ldap_url))
  LDAP_USER: ((ldap_user))
  LDAP_PWD: ((ldap_pwd))
  SEARCH_BASE: ((search_base))
  SEARCH_FILTER: ((search_filter))
  GROUP_SEARCH_BASE: ((group_search_base))
  GROUP_SEARCH_FILTER: ((group_search_filter))
  MAIL_ATTR_NAME: ((mail_attribute_name))
  FIRST_NAME_ATTR: ((first_name_attribute))
  LAST_NAME_ATTR: ((last_name_attribute))
  SECURITY_ACKNOWLEDGEMENT: ((security_acknowledgement))
  SYSTEM_DOMAIN: ((system_domain))
  APPS_DOMAIN: ((apps_domain))
  DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB: ((default_quota_memory_limit_mb))
  DEFAULT_QUOTA_MAX_SERVICES_COUNT: ((default_quota_max_number_services))
  HA_PROXY_IPS: ((ha_proxy_ips))
  SKIP_CERT_VERIFY: ((skip_cert_verify))
  DISABLE_INSECURE_COOKIES: ((disable_insecure_cookies))
  ROUTER_STATIC_IPS: ((router_static_ips))
  ROUTER_REQUEST_TIMEOUT_IN_SEC: ((router_request_timeout_in_seconds))
  GARDEN_NETWORK_POOL_CIDR: ((garden_network_pool_cidr))
  GARDEN_NETWORK_MTU: ((garden_network_mtu))
  MYSQL_MONITOR_EMAIL: ((mysql_monitor_email))
  MYSQL_BACKUPS: ((mysql_backups))
  MYSQL_BACKUPS_SCP_SERVER: ((mysql_backups_scp_server))
  MYSQL_BACKUPS_SCP_PORT: ((mysql_backups_scp_port))
  MYSQL_BACKUPS_SCP_USER: ((mysql_backups_scp_user))
  MYSQL_BACKUPS_SCP_KEY: ((mysql_backups_scp_key))
  MYSQL_BACKUPS_SCP_DESTINATION: ((mysql_backups_scp_destination))
  MYSQL_BACKUPS_SCP_CRON_SCHEDULE: ((mysql_backups_scp_cron_schedule))
  MYSQL_BACKUPS_S3_ENDPOINT_URL: ((mysql_backups_s3_endpoint_url))
  MYSQL_BACKUPS_S3_BUCKET_NAME: ((mysql_backups_s3_bucket_name))
  MYSQL_BACKUPS_S3_BUCKET_PATH: ((mysql_backups_s3_bucket_path))
  MYSQL_BACKUPS_S3_ACCESS_KEY_ID: ((mysql_backups_s3_access_key_id))
  MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: ((mysql_backups_s3_secret_access_key))
  MYSQL_BACKUPS_S3_CRON_SCHEDULE: ((mysql_backups_s3_cron_schedule))
  ALLOW_APP_SSH_ACCESS: ((allow_app_ssh_access))
  TCP_ROUTER_STATIC_IPS: ((tcp_router_static_ips))
  SSH_STATIC_IPS: ((ssh_static_ips))
  CONSUL_SERVER_INSTANCES: ((consul_server_instances))
  NATS_INSTANCES: ((nats_instances))
  NFS_SERVER_INSTANCES: ((nfs_server_instances))
  MYSQL_PROXY_INSTANCES: ((mysql_proxy_instances))
  MYSQL_INSTANCES: ((mysql_instances))
  BACKUP_PREPARE_INSTANCES: ((backup_prepare_instances))
  UAA_INSTANCES: ((uaa_instances))
  CLOUD_CONTROLLER_INSTANCES: ((cloud_controller_instances))
  HA_PROXY_INSTANCES: ((ha_proxy_instances))
  ROUTER_INSTANCES: ((router_instances))
  MYSQL_MONITOR_INSTANCES: ((mysql_monitor_instances))
  CREDHUB_INSTANCES: ((credhub_instances))
  CLOCK_GLOBAL_INSTANCES: ((clock_global_instances))
  CLOUD_CONTROLLER_WORKER_INSTANCES: ((cloud_controller_worker_instances))
  DIEGO_DATABASE_INSTANCES: ((diego_database_instances))
  DIEGO_BRAIN_INSTANCES: ((diego_brain_instances))
  DIEGO_CELL_INSTANCES: ((diego_cell_instances))
  DOPPLER_INSTANCES: ((doppler_instances))
  LOGGREGATOR_TC_INSTANCES: ((loggregator_traffic_controller_instances))
  TCP_ROUTER_INSTANCES: ((tcp_router_instances))
  SYSLOG_ADAPTER_INSTANCES: ((syslog_adapter_instances))
  SYSLOG_SCHEDULER_INSTANCES: ((syslog_scheduler_instances))
  INTERNET_CONNECTED: ((internet_connected))
  CONTAINER_NETWORKING_NW_CIDR: ((container_networking_nw_cidr))
  ROUTER_NSX_SECURITY_GROUP: ((router_nsx_security_group))
  TCP_ROUTER_NSX_SECURITY_GROUP: ((tcp_router_nsx_security_group))
  DIEGO_BRAIN_NSX_SECURITY_GROUP: ((diego_brain_nsx_security_group))
  MYSQL_PROXY_NSX_SECURITY_GROUP: ((mysql_proxy_nsx_security_group))
  HA_PROXY_LB_NAME: ""
  HAPROXY_FLOATING_IPS: ""
  CONTAINER_NETWORKING_INTERFACE_PLUGIN: ((container_networking_interface_plugin))
  CREDHUB_PASSWORD: ((credhub_password))
  BLOBSTORE_INTERNAL_ACCESS_SUBNET: ((blobstore_internal_access_subnet))
  ENABLE_GROOTFS: ((enable_grootfs))
  ROUTING_SSL_TERMINATOR: ((routing_ssl_terminator))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master

- name: nsx-t-ci-pipeline
  type: git
  source:
    uri: https://github.com/rpletka/nsx-t-ci-pipeline.git
    branch: master

- name: pcf-ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: ((opsman_major_minor_version))
    sort_by: semver

- name: elastic-runtime
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ((ert_major_minor_version))
    sort_by: semver

- name: nsx-t-add-on-tile
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: vmware-nsx-t
    product_version: ((nsxt_major_minor_version))
    sort_by: semver


groups:

- name: full-pas-install
  jobs:
  - deploy-opsman
  - configure-director
  - deploy-director
  - upload-nsx
  - configure-nsx
  - upload-ert
  - deploy-ert

- name: ops-mgr-install
  jobs:
  - deploy-opsman
  - configure-director
  - deploy-director

- name: wipe
  jobs:
  - wipe-env

jobs:

- name: deploy-opsman
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsman-product
      resource: pcf-ops-manager
      params: {globs: ["*.ova"]}

  - task: deploy
    file: pcf-pipelines/install-pcf/vsphere/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((om_data_store))
      GOVC_NETWORK: ((om_vm_network))
      GOVC_RESOURCE_POOL: ((om_resource_pool))
      GOVC_HOST: ((om_vm_host))
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPS_MGR_SSH_PWD: ((om_ssh_pwd))
      OM_NTP_SERVERS: ((om_ntp_servers))
      OM_DNS_SERVERS: ((om_dns_servers))
      OM_GATEWAY: ((om_gateway))
      OM_NETMASK: ((om_netmask))
      OM_IP: ((om_ip))
      OM_VM_NETWORK: ((om_vm_network))
      OM_VM_NAME: ((om_vm_name))
      OM_RESOURCE_POOL: ((om_resource_pool))
      OPSMAN_DISK_TYPE: ((opsman_disk_type))
      OM_VM_POWER_STATE: ((om_vm_power_state))

- name: configure-director
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: nsx-t-ci-pipeline
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-opsman]
      trigger: true

  - task: config-opsman-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      OPS_MGR_USR: ((opsman_admin_username))
      OPS_MGR_PWD: ((opsman_admin_password))
      OM_DECRYPTION_PWD: ((om_decryption_pwd))

  - task: configure-director
    file: nsx-t-ci-pipeline/tasks/config-opsdir-2.0/task.yml
    params: *ops-dir-config-params

- name: deploy-director
  plan:
  - aggregate:
    - get: nsx-t-ci-pipeline
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [configure-director]
      trigger: true

  - task: apply-changes
    file: nsx-t-ci-pipeline/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))

# # Use s3 if the tile bit is not available on Pivnet
# - name: upload-nsx
#   plan:
#   - aggregate:
#     - get: nsx-t-ci-pipeline
#     - get: s3-tile
#       resource: nsx-t-add-on-tile
#     - get: pcf-ops-manager
#       params: {globs: []}
#       passed: [deploy-director]
#       trigger: true

#   - task: upload-nsx-tile
#     file: nsx-t-ci-pipeline/tasks/upload-s3-tile/task.yml
#     params:
#       OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
#       OPSMAN_USERNAME: ((opsman_admin_username))
#       OPSMAN_PASSWORD: ((opsman_admin_password))

- name: upload-nsx
  plan:
  - aggregate:
    - get: nsx-t-ci-pipeline
    - get: pivnet-product
      resource: nsx-t-add-on-tile
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-director]
      trigger: true

  - task: upload-nsx-tile
    file: nsx-t-ci-pipeline/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: "vsphere"
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      PIVNET_API_TOKEN: ((pivnet_token))
      OM_IP: ((om_ip))

- name: configure-nsx
  plan:
  - aggregate:
    - get: nsx-t-ci-pipeline
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [upload-nsx]
      trigger: true
    - get: pivnet-product
      resource: nsx-t-add-on-tile
      params: {globs: []}

  - task: validate-nsx-config-for-pas
    file: nsx-t-ci-pipeline/tasks/validate-nsx-t-for-pas/task.yml
    params:
      NSX_API_MANAGER: ((nsx_address))
      NSX_API_USER: ((nsx_username))
      NSX_API_PASSWORD: ((nsx_password))
      NSX_FOUNDATION_NAME: ((nsx_foundation_name))
      NSX_T_OVERLAY_TRANSPORT_ZONE: ((nsx_t_overlay_transport_zone))
      NSX_T_T0ROUTER_NAME: ((nsx_t_t0router_name))
      NSX_T_CONTAINER_IP_BLOCK_SPEC: ((nsx_t_container_ip_block_spec))
      NSX_T_EXTERNAL_IP_POOL_SPEC: ((nsx_t_external_ip_pool_spec))

  - task: configure-nsx
    file: nsx-t-ci-pipeline/tasks/config-nsx-t/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      NSX_API_MANAGERS: ((nsx_address))
      NSX_API_USER: ((nsx_username))
      NSX_API_PASSWORD: ((nsx_password))
      NSX_FOUNDATION_NAME: ((nsx_foundation_name))
      NSX_NCP_DEBUG_LOG: ((nsx_ncp_debug_log))
      NSX_SUBNET_PREFIX: ((nsx_subnet_prefix))
      NSX_LOG_DROPPED_TRAFFIC: ((nsx_log_dropped_traffic))
      NSX_ENABLE_SNAT: ((nsx_enable_snat))
      NSX_EXTERNAL_SUBNET_PREFIX: ((nsx_external_subnet_prefix))
      NSX_PRODUCT_TILE_NAME: ((nsx_product_tile_name))
      NSX_AUTH_TYPE: ((nsx_auth_type))
      NSX_CLIENT_CERT_CERT: ((nsx_client_cert_cert))
      NSX_CLIENT_CERT_PRIVATE_KEY: ((nsx_client_cert_private_key))
      NSX_T_OVERLAY_TRANSPORT_ZONE: ((nsx_t_overlay_transport_zone))
      NSX_T_T0ROUTER_NAME: ((nsx_t_t0router_name))
      NSX_T_CONTAINER_IP_BLOCK_SPEC: ((nsx_t_container_ip_block_spec))
      NSX_T_EXTERNAL_IP_POOL_SPEC: ((nsx_t_external_ip_pool_spec))

- name: upload-ert
  plan:
  - aggregate:
    - get: nsx-t-ci-pipeline
    - get: pivnet-product
      resource: elastic-runtime
      params: {globs: ["cf*.pivotal"]}
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-director, configure-nsx]
      trigger: true

  - task: upload-tile
    file: nsx-t-ci-pipeline/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: "vsphere"
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      PIVNET_API_TOKEN: ((pivnet_token))
      OM_IP: ((om_ip))

- name: deploy-ert
  plan:
  - aggregate:
    - get: nsx-t-ci-pipeline
    - get: pcf-pipelines
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [upload-ert]
      trigger: true

  - task: configure-ert
    file: nsx-t-ci-pipeline/tasks/config-ert-2.0/task.yml
    params: *ert-config-params

  - task: configure-errands
    file: nsx-t-ci-pipeline/tasks/config-errands/task.yml
    params:
      PRODUCT_NAME: cf
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      ERRANDS_TO_RUN_ON_CHANGE: ((ert_errands_to_run_on_change))

  - task: deploy-ert
    file: nsx-t-ci-pipeline/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))

- name: wipe-env
  plan:
  - aggregate:
    - get: nsx-t-ci-pipeline
  - task: wipe
    file: nsx-t-ci-pipeline/tasks/wipe-env/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      OPSMAN_IP: ((om_ip))
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((om_data_store))
      GOVC_NETWORK: ((om_vm_network))
      GOVC_RESOURCE_POOL: ((om_resource_pool))
      GOVC_HOST: ((om_vm_host))
